// <auto-generated />
namespace Rental_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SeedingDataIntoMembershipTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedingDataIntoMembershipTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201705171341552_SeedingDataIntoMembershipTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
